RXI-893 Change owning model to guarantee destroying sequence
ripple/xbridge_witness pull request #104
Opened 2024-05-06 22:07 UTC by oleks-rip

2024-05-07 21:28 UTC, seelabs requested changes
I'm not following how this is safe - it looks like destroyed objects could be accessed in asio during system shutdown. But I didn't dig in too deeply, I thought I'd ask for an explanation for why this is safe first.

The commit message is too terse. The commit message should explain why it is safe to make this change.

2024-05-07 21:28 UTC, seelabs commented on src/xbwd/federator/Federator.cpp
>      r->init(ios, config, l);
The motivation for the "make_Federator" and the separation of the constructor into a constructor and an init was to satisfy the constraints around "shared_from_this". If the shared pointers are going away, then this can be simplified.

2024-05-07 21:28 UTC, seelabs commented on src/xbwd/client/WebsocketClient.h
> +    std::atomic_uint32_t nextId_{0};
I prefer the template versions of these functions, but also OK as-is.

2024-05-07 21:28 UTC, seelabs commented on src/xbwd/client/WebsocketClient.cpp
> -    timer_.async_wait([wptr](boost::system::error_code const& ec) {
I see several places where a shared or a weak pointer was replaced with a naked `this` in a callback. The motivation for the shared/weak pointers was to make sure we don't access a destroyed object in asio. For example, during shutdown, the app is destroyed before asio. Aren't we in danger of accessing destroyed objects?

2024-05-08 16:26 UTC, oleks-rip commented on src/xbwd/federator/Federator.cpp
>      r->init(ios, config, l);
Now Chain listener wait for websocketclient destructor. And websocketclient destructor will cancel all the io operations, and wait for it. So when destructor finish, no pending operations left. Then federator wait for both chainlisteners, and app wait for federator. These changes are to be ensure that when we destroy  the local object, it is actually destroyed and there are no side effects caused by callbacks from the io operations.

2024-05-08 16:27 UTC, oleks-rip commented on src/xbwd/client/WebsocketClient.h
> +    std::atomic_uint32_t nextId_{0};
There are both in the code, so I refactor them when I see one.

2024-05-08 16:28 UTC, oleks-rip commented on src/xbwd/client/WebsocketClient.cpp
> -    timer_.async_wait([wptr](boost::system::error_code const& ec) {
Now we manually cancel all the io operations in the websocketclient destructor, and waiting for their cancellation

2024-05-08 16:57 UTC, seelabs approved these changes
:+1:

2024-05-14 21:14 UTC, merged