GitHub Sctions refactor
ripple/xbridge_witness pull request #105
Opened 2024-05-13 23:22 UTC by legleux

Run `clang-format`

Adds builds for:
- GCC 11
- Clang 14
- AppleClang 15

Runs unit tests
Removed Docker image publish. Adding it in a new action in subsequent PR.
Moved Linux packaging to different repository

2024-05-14 18:00 UTC, legleux commented
[macOS failure](https://github.com/ripple/xbridge_witness/actions/runs/9083346308/job/24961842278?pr=105) is expected at the moment.

Hopefully this addition can prevent that in the future.

2024-05-14 21:04 UTC, oleks-rip requested changes

2024-05-14 21:04 UTC, oleks-rip commented on src/xbwd/app/main.cpp
> +        std::unique_ptr<xbwd::config::Config> config = [&]() -> auto
Original version is correctly clang-formatted.

2024-05-14 21:04 UTC, oleks-rip commented on src/xbwd/app/main.cpp
> +        ();
Same here. It was already clang-formatted. Change is not clang formatted.

2024-05-14 22:27 UTC, legleux commented on src/xbwd/app/main.cpp
> +        ();
This _does_ look like a peculiar formatting decision.
Is the config not being used or is the command being run not correct?
I just copied what `rippled` has. This is `clang-format-10`

```bash
find src/xbwd -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.ipp' \) -print0 | xargs -0 clang-format-${CLANG_VERSION} -i
```
https://github.com/legleux/xbridge_witness/blob/4f9643a4fae1b9cbb3c0c26244fb231f7bf0655d/.github/workflows/clang-format.yml#L23

2024-05-16 00:31 UTC, legleux commented on src/xbwd/app/main.cpp
> +        std::unique_ptr<xbwd::config::Config> config = [&]() -> auto
Looks like that patch fixed up the weird dangling `();`

2024-05-16 14:49 UTC, oleks-rip approved these changes

2024-05-16 16:25 UTC, seelabs approved these changes

2024-05-17 07:05 UTC, merged